apiVersion: v1
kind: Namespace
metadata:
  name: k8s-text-analysis

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: cephfs-pvc-k8s-text-analysis
    namespace: k8s-text-analysis
spec:
    accessModes:
    - ReadWriteMany
    resources:
        requests:
            storage: 1Gi
    storageClassName: rook-cephfs

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-master-deployment
    namespace: k8s-text-analysis
    labels:
        app: redis
spec:
    replicas: 1
    selector:
        matchLabels:
            app: redis
    template:
        metadata:
            namespace: k8s-text-analysis
            labels:
                app: redis
        spec:
            containers:
            - name: master
              image: redis
              env:
              - name: MASTER
                value: "true"
              ports:
                - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
    name: redis
    namespace: k8s-text-analysis
spec:
    ports:
        - port: 6379
          targetPort: 6379
    selector:
        app: redis
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: ceph-fs-interface-deployment
    namespace: k8s-text-analysis
    labels:
        app: ceph-fs-interface
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ceph-fs-interface
    template:
        metadata:
            namespace: k8s-text-analysis
            labels:
                app: ceph-fs-interface
        spec:
            containers:
                - name: ceph-fs-interface
                  image: jordan396/persistent-alpine:v1
                  volumeMounts:
                  - name: ceph-filesystem
                    mountPath: /mnt/ceph-filesystem
            volumes:
                - name: ceph-filesystem
                  persistentVolumeClaim:
                    claimName: cephfs-pvc-k8s-text-analysis
                    readOnly: false