apiVersion: batch/v1
kind: Job
metadata:
  name: clear-filesystem-job
  namespace: k8s-text-analysis
spec:
  template:
    metadata:
      name: clear-filesystem-job
      namespace: k8s-text-analysis
    spec:
      containers:
      - name: clear-filesystem-job
        image: jordan396/k8s-text-analysis-clear-filesystem:latest
        volumeMounts:
          - name: ceph-filesystem
            mountPath: /mnt/ceph-filesystem
      volumes:
        - name: ceph-filesystem
          persistentVolumeClaim:
            claimName: cephfs-pvc-k8s-text-analysis
            readOnly: false
      restartPolicy: OnFailure